// Builds the Workers bundle.
//
// Two steps: freeze `shared/` into a module (a Worker has no filesystem, and
// inlining ~40 KB of text avoids the separate assets-upload dance entirely),
// then bundle everything reachable from entry.ts into one ES module.
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";

const here = new URL(".", import.meta.url).pathname;
const shared = `${here}../shared`;

const names = (await readdir(shared)).sort();
const bundle: Record<string, string> = {};
for (const n of names) bundle[n] = await readFile(`${shared}/${n}`, "utf8");

// Gzipped, not inlined verbatim. The deploy path is a JSON API call carrying
// the whole script, and 40 KB of HTML/CSS/JS as source text dominated it;
// gzip+base64 is about a quarter of that, and Workers can inflate it with the
// DecompressionStream the platform already provides.
const raw = new TextEncoder().encode(JSON.stringify(bundle));
const gz = Bun.gzipSync(raw);
const b64 = Buffer.from(gz).toString("base64");
await writeFile(
  `${here}assets.ts`,
  `// GENERATED by build.ts from ../shared — do not edit.\n` +
    `// A Worker has no filesystem, so the port's static files ship inside the\n` +
    `// bundle, gzipped (see build.ts for why) and inflated once at startup.\n` +
    `export const ASSETS_GZIP_BASE64 =\n  ${JSON.stringify(b64)};\n`,
);
console.log(`assets: ${names.length} files, ${raw.length} -> ${gz.length} gz -> ${b64.length} b64`);

await mkdir(`${here}dist`, { recursive: true });
const out = await Bun.build({
  entrypoints: [`${here}entry.ts`],
  outdir: `${here}dist`,
  target: "browser",
  format: "esm",
  minify: true,
  naming: "[dir]/[name].mjs",
});
if (!out.success) {
  for (const log of out.logs) console.error(log);
  process.exit(1);
}
for (const artifact of out.outputs) {
  console.log(`${artifact.path.split("/").pop()}: ${(await artifact.text()).length} bytes`);
}
